const WHITE = "#ffffff";
const FLINT_STONE = "#2f353b";
const FLINT_STONE_LIGHT = "#66708580";
const BLACK = "#000000";
const BLUE_LOBSTER = "#004FAB";
const THEME = "#0EAD0E";
const PINBALL = "#D3D3D3";
const WHITE_SMOKE = "#F5F5F5";
const WILD_DOVE = "#8B8B8B";
const BERN_RED = "#ff0505";
const JASPER_CANE = "#E8E8E8";
const VITAMIN_C = "#FF9900";
const BLACK_GREY = "#24282D";
const FRIENDLY_BASILISK = "#0EAD0E30";
const TROLLEY_GREY = `#818181`;
const BLACK_VELVET = `#212331`;
const HARVARD_CRIMSON = `#c90016`;
const SPANDEX_GREEN = "#34A853";
const LIGHT_GREY = "#667085";

export {
  LIGHT_GREY,
  WHITE,
  FLINT_STONE,
  FLINT_STONE_LIGHT,
  BLACK,
  BLUE_LOBSTER,
  THEME,
  PINBALL,
  WHITE_SMOKE,
  WILD_DOVE,
  BERN_RED,
  JASPER_CANE,
  VITAMIN_C,
  BLACK_GREY,
  FRIENDLY_BASILISK,
  SPANDEX_GREEN,
  TROLLEY_GREY,
  BLACK_VELVET,
  HARVARD_CRIMSON,
};
