import { ToastPosition } from "@backpackapp-io/react-native-toast";

export const mask = [
  "(",
  /\d/,
  /\d/,
  /\d/,
  ")",
  " ",
  /\d/,
  /\d/,
  /\d/,
  "-",
  /\d/,
  /\d/,
  /\d/,
  /\d/,
];

export const tabHiddenRoutes = [
  "TripDetail",
  "ContactUs",
  "Feedback",
  "PaymentMethods",
  "MyProfile",
  "ChangePhone",
  "Password",
  "FuelStationDetail",
  "GetDirection",
  "SaasFuelStationDetail",
  "SaasConnectorDetail",
  "AppInfo",
  "ChargingActivities",
  "ChargingDetail",
  "SaasFuelStationStopCharging",
  "Notification",
];

export const networkTypeData = [
  { id: 1, label: "All", value: "all", isSelected: true },
  {
    id: 1,
    label: "AddÉnergie",
    value: "AddÉnergie Technologies",
    isSelected: false,
  },
  { id: 1, label: "AmpUp", value: "AMPUP", isSelected: false },
  { id: 1, label: "BC Hydro", value: "BCHYDRO", isSelected: false },
  { id: 1, label: "Blink", value: "Blink Network", isSelected: false },
  { id: 1, label: "ChargeLab", value: "CHARGELAB", isSelected: false },
  {
    id: 1,
    label: "ChargePoint",
    value: "ChargePoint Network",
    isSelected: false,
  },
  { id: 1, label: "CircleK Charge", value: "CIRCLE_K", isSelected: false },
  {
    id: 1,
    label: "CircleK/Couche-Tard Recharge",
    value: "COUCHE_TARD",
    isSelected: false,
  },
  {
    id: 1,
    label: "Circuit électrique",
    value: "Circuit électrique",
    isSelected: false,
  },
  {
    id: 1,
    label: "ECharge Network",
    value: "eCharge Network",
    isSelected: false,
  },
  {
    id: 1,
    label: "Electrify America",
    value: "Electrify America",
    isSelected: false,
  },
  {
    id: 1,
    label: "Electrify Canada",
    value: "Electrify Canada",
    isSelected: false,
  },
  { id: 1, label: "EV Charging Solutions", value: "EVCS", isSelected: false },
  { id: 1, label: "EV Connect", value: "EV Connect", isSelected: false },
  { id: 1, label: "evGateway", value: "EVGATEWAY", isSelected: false },
  { id: 1, label: "EVgo", value: "eVgo Network", isSelected: false },
  { id: 1, label: "EV Range", value: "EVRANGE", isSelected: false },
  { id: 1, label: "FLASH", value: "FLASH", isSelected: false },
  { id: 1, label: "FLO", value: "FLO", isSelected: false },
  { id: 1, label: "FPL EVolution", value: "FPLEV", isSelected: false },
  { id: 1, label: "Francis", value: "FCN", isSelected: false },
  { id: 1, label: "Ivy", value: "IVY", isSelected: false },
  {
    id: 1,
    label: "Livingston Energy Group",
    value: "LIVINGSTON",
    isSelected: false,
  },
  { id: 1, label: "Non-Networked", value: "Non-Networked", isSelected: false },
  { id: 1, label: "OpConnect", value: "OpConnect", isSelected: false },
  { id: 1, label: "Petro-Canada", value: "PETROCAN", isSelected: false },
  { id: 1, label: "PowerFlex", value: "POWERFLEX", isSelected: false },
  { id: 1, label: "Red E Charging", value: "RED_E", isSelected: false },
  {
    id: 1,
    label: "Rivian Adventure Network",
    value: "RIVIAN_ADVENTURE",
    isSelected: false,
  },
  {
    id: 1,
    label: "Rivian Waypoints",
    value: "RIVIAN_WAYPOINTS",
    isSelected: false,
  },
  {
    id: 1,
    label: "SemaConnect",
    value: "SemaCharge Network",
    isSelected: false,
  },
  {
    id: 1,
    label: "Shell Recharge",
    value: "SHELL_RECHARGE",
    isSelected: false,
  },
  {
    id: 1,
    label: "Sun Country Highway",
    value: "Sun Country Highway",
    isSelected: false,
  },
  { id: 1, label: "Swtch Energy", value: "SWTCH", isSelected: false },
  {
    id: 1,
    label: "Tesla Destination",
    value: "Tesla Destination",
    isSelected: false,
  },
  { id: 1, label: "Tesla Supercharger", value: "Tesla", isSelected: false },
  {
    id: 1,
    label: "Universal EV Chargers",
    value: "UNIVERSAL",
    isSelected: false,
  },
  { id: 1, label: "Volta", value: "Volta", isSelected: false },
  { id: 1, label: "WAVE", value: "WAVE", isSelected: false },
  { id: 1, label: "Webasto", value: "Webasto", isSelected: false },
  { id: 1, label: "ZEF Network", value: "ZEFNET", isSelected: false },
];

export const connectorTypeData = [
  { id: 0, label: "All", value: "all", isSelected: true },
  { id: 0, label: "NEMA 14-50", value: "NEMA1450", isSelected: false },
  { id: 0, label: "NEMA 5-15", value: "NEMA515", isSelected: false },
  { id: 0, label: "NEMA 5-20", value: "NEMA520", isSelected: false },
  { id: 0, label: "J1772", value: "J1772", isSelected: false },
  { id: 0, label: "CCS", value: "J1772COMBO", isSelected: false },
  { id: 0, label: "CHAdeMO", value: "CHADEMO", isSelected: false },
  { id: 0, label: "Tesla", value: "TESLA", isSelected: false },
];

export const singleImageOption = {
  quality: 1,
  allowsEditing: false,
  noData: true,
  storageOptions: { skipBackup: true },
  maxWidth: 500,
  maxHeight: 500,
};

export const multiImageOptions = {
  quality: 1,
  allowsEditing: false,
  noData: true,
  storageOptions: { skipBackup: true },
  maxWidth: 500,
  maxHeight: 500,
  selectionLimit: 5,
};

export const singleImageOptions = {
  quality: 1,
  allowsEditing: false,
  noData: true,
  storageOptions: { skipBackup: true },
  maxWidth: 500,
  maxHeight: 500,
};

export const statesData = [
  { id: 0, label: "Alaska", value: "Alaska" },
  { id: 1, label: "Alabama", value: "Alabama" },
  { id: 2, label: "Arkansas", value: "Arkansas" },
  { id: 3, label: "American Samoa", value: "American Samoa" },
  { id: 4, label: "Arizona", value: "Arizona" },
  { id: 5, label: "California", value: "California" },
  { id: 6, label: "Colorado", value: "Colorado" },
  { id: 7, label: "Connecticut", value: "Connecticut" },
  { id: 8, label: "District of Columbia", value: "District of Columbia" },
  { id: 9, label: "Delaware", value: "Delaware" },
  { id: 10, label: "Florida", value: "Florida" },
  { id: 11, label: "Georgia", value: "Georgia" },
  { id: 12, label: "Guam", value: "Guam" },
  { id: 13, label: "Hawaii", value: "Hawaii" },
  { id: 14, label: "Iowa", value: "Iowa" },
  { id: 15, label: "Idaho", value: "Idaho" },
  { id: 16, label: "Illinois", value: "Illinois" },
  { id: 17, label: "Indiana", value: "Indiana" },
  { id: 18, label: "Kansas", value: "Kansas" },
  { id: 19, label: "Kentucky", value: "Kentucky" },
  { id: 20, label: "Louisiana", value: "Louisiana" },
  { id: 21, label: "Massachusetts", value: "Massachusetts" },
  { id: 22, label: "Maryland", value: "Maryland" },
  { id: 23, label: "Maine", value: "Maine" },
  { id: 24, label: "Michigan", value: "Michigan" },
  { id: 25, label: "Minnesota", value: "Minnesota" },
  { id: 26, label: "Missouri", value: "Missouri" },
  { id: 27, label: "Mississippi", value: "Mississippi" },
  { id: 28, label: "Montana", value: "Montana" },
  { id: 29, label: "North Carolina", value: "North Carolina" },
  { id: 30, label: "North Dakota", value: "North Dakota" },
  { id: 31, label: "Nebraska", value: "Nebraska" },
  { id: 32, label: "New Hampshire", value: "New Hampshire" },
  { id: 33, label: "New Jersey", value: "New Jersey" },
  { id: 34, label: "New Mexico", value: "New Mexico" },
  { id: 35, label: "Nevada", value: "Nevada" },
  { id: 36, label: "New York", value: "New York" },
  { id: 37, label: "Ohio", value: "Ohio" },
  { id: 38, label: "Oklahoma", value: "Oklahoma" },
  { id: 39, label: "Oregon", value: "Oregon" },
  { id: 40, label: "Pennsylvania", value: "Pennsylvania" },
  { id: 41, label: "Puerto Rico", value: "Puerto Rico" },
  { id: 42, label: "Rhode Island", value: "Rhode Island" },
  { id: 43, label: "South Carolina", value: "South Carolina" },
  { id: 44, label: "South Dakota", value: "South Dakota" },
  { id: 45, label: "Tennessee", value: "Tennessee" },
  { id: 46, label: "Texas", value: "Texas" },
  { id: 47, label: "Utah", value: "Utah" },
  { id: 48, label: "Virginia", value: "Virginia" },
  { id: 49, label: "Virgin Islands", value: "Virgin Islands" },
  { id: 50, label: "Vermont", value: "Vermont" },
  { id: 51, label: "Washington", value: "Washington" },
  { id: 52, label: "Wisconsin", value: "Wisconsin" },
  { id: 53, label: "West Virginia", value: "West Virginia" },
  { id: 54, label: "Wyoming", value: "Wyoming" },
];

export const ownerTypeData = [
  { id: 1, label: "All", value: "all" },
  { id: 2, label: "Federal Government Owned", value: "FG" },
  { id: 3, label: "Jointly Owned", value: "J" },
  { id: 4, label: "Local/Municipal Government Owned", value: "LG" },
  { id: 5, label: "Privately Owned", value: "P" },
  { id: 6, label: "State/Provincial Government Owned", value: "SG" },
  { id: 7, label: "Utility Owned", value: "T" },
];

export const fuelTypeData = [
  { id: 1, label: "All", value: "all" },
  { id: 2, label: "Biodiesel (B20 and above)", value: "BD" },
  { id: 3, label: "Compressed Natural Gas (CNG)", value: "CNG" },
  { id: 4, label: "Electric", value: "ELEC" },
  { id: 5, label: "Ethanol (E85)", value: "E85" },
  { id: 6, label: "Hydrogen", value: "HY" },
  { id: 7, label: "Liquefied Natural Gas (LNG)", value: "LNG" },
  { id: 8, label: "Propane (LPG)", value: "LPG" },
  { id: 9, label: "Renewable Diesel (R20 and above)", value: "RD" },
];

export const radiusData = [
  { id: 1, label: "25 Miles", value: "25" },
  { id: 2, label: "50 Miles", value: "50" },
  { id: 3, label: "75 Miles", value: "75" },
  { id: 4, label: "100 Miles", value: "100" },
];

export const textInputBorderRound = 22;

export const toastConfig = {
  position: ToastPosition.BOTTOM,
}