export const CHARGER_STATUSES = {
  AVAILABLE: 'AVAILABLE',
  PREPARING: 'PREPARING',
  CHARGING: 'CHARGING',
  SUSPENDED_EV: 'Suspended_EV',
  SUSPENDED_EVSE: 'Suspended_EVSE',
  FINISHED: 'FINISHED',
  FINISHING: 'FINISHING',
  RESERVED: 'Reserved',
  FAULTED: 'FAULTED',
  UNAVAILABLE: 'UNAVAILABLE',
};
